services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.26.8
    container_name: studyflow-n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    env_file:
      - n8n.env

    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678/

      GENERIC_TIMEZONE: Asia/Karachi
      TZ: Asia/Karachi

      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"

      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: